name: js-monitoring

services:
  web:
    build: .
    container_name: ml_final-fastapi-monitoring
    volumes:
      - .:/code
    ports:
      - "5000:80"
    environment:
      - ENABLE_METRICS=true